# Setup
title:               Final Project Blog
tagline:             'Weekly Logs'
description:         'Draft Blog for weekly logs'
url:                 Link to gitlab
baseurl:             'progress-blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Cem Kose
  url:               Link to gitlab
  email:             ckose001@gold.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.2.0
google_analytics_id: #UA-XXXX-Y
